
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Article
* GENERATION DATE:  22.07.2015
* CLASS FILE:       C:\xampp\htdocs\sql_class_generator-2006-01-02/generated_classes/class.Article.php
* FOR MYSQL TABLE:  tblarticle
* FOR MYSQL DB:     easy-cms-bdd
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("../../lib/sql_class_generator-2006-01-02/resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

//App::uses('Article', 'Model');

class Article extends AppModel
{
}
?>
<!-- end of generated class -->
