
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Comment
* GENERATION DATE:  22.07.2015
* CLASS FILE:       C:\xampp\htdocs\sql_class_generator-2006-01-02/generated_classes/class.Comment.php
* FOR MYSQL TABLE:  tblcomment
* FOR MYSQL DB:     easy-cms-bdd
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("../../lib/sql_class_generator-2006-01-02/resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

//App::uses('Comment', 'Model');

class Comment  extends AppModel
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $CommentID;   // KEY ATTR. WITH AUTOINCREMENT

var $UserID;   // (normal Attribute)
var $Content;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Comment()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getCommentID()
{
return $this->CommentID;
}

function getUserID()
{
return $this->UserID;
}

function getContent()
{
return $this->Content;
}

// **********************
// SETTER METHODS
// **********************


function setCommentID($val)
{
$this->CommentID =  $val;
}

function setUserID($val)
{
$this->UserID =  $val;
}

function setContent($val)
{
$this->Content =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM tblcomment WHERE CommentID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->CommentID = $row->CommentID;

$this->UserID = $row->UserID;

$this->Content = $row->Content;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM tblcomment WHERE CommentID = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->CommentID = ""; // clear key for autoincrement

$sql = "INSERT INTO tblcomment ( UserID,Content ) VALUES ( '$this->UserID','$this->Content' )";
$result = $this->database->query($sql);
$this->CommentID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE tblcomment SET  UserID = '$this->UserID',Content = '$this->Content' WHERE CommentID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
