
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        LineOrder
* GENERATION DATE:  22.07.2015
* CLASS FILE:       C:\xampp\htdocs\sql_class_generator-2006-01-02/generated_classes/class.LineOrder.php
* FOR MYSQL TABLE:  tbllineorder
* FOR MYSQL DB:     easy-cms-bdd
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("../../lib/sql_class_generator-2006-01-02/resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

//App::uses('LineOrder', 'Model');

class LineOrder  extends AppModel
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $LineOrderID;   // KEY ATTR. WITH AUTOINCREMENT

var $OrderID;   // (normal Attribute)
var $ArticleID;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function LineOrder()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getLineOrderID()
{
return $this->LineOrderID;
}

function getOrderID()
{
return $this->OrderID;
}

function getArticleID()
{
return $this->ArticleID;
}

// **********************
// SETTER METHODS
// **********************


function setLineOrderID($val)
{
$this->LineOrderID =  $val;
}

function setOrderID($val)
{
$this->OrderID =  $val;
}

function setArticleID($val)
{
$this->ArticleID =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM tbllineorder WHERE LineOrderID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->LineOrderID = $row->LineOrderID;

$this->OrderID = $row->OrderID;

$this->ArticleID = $row->ArticleID;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM tbllineorder WHERE LineOrderID = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->LineOrderID = ""; // clear key for autoincrement

$sql = "INSERT INTO tbllineorder ( OrderID,ArticleID ) VALUES ( '$this->OrderID','$this->ArticleID' )";
$result = $this->database->query($sql);
$this->LineOrderID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE tbllineorder SET  OrderID = '$this->OrderID',ArticleID = '$this->ArticleID' WHERE LineOrderID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
