
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Storage
* GENERATION DATE:  22.07.2015
* CLASS FILE:       C:\xampp\htdocs\sql_class_generator-2006-01-02/generated_classes/class.Storage.php
* FOR MYSQL TABLE:  tblstorage
* FOR MYSQL DB:     easy-cms-bdd
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************
App::uses('Storage', 'Model');

class Storage  extends AppModel
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $StorageID;   // KEY ATTR. WITH AUTOINCREMENT

var $ArticleID;   // (normal Attribute)
var $StorageCount;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Storage()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getStorageID()
{
return $this->StorageID;
}

function getArticleID()
{
return $this->ArticleID;
}

function getStorageCount()
{
return $this->StorageCount;
}

// **********************
// SETTER METHODS
// **********************


function setStorageID($val)
{
$this->StorageID =  $val;
}

function setArticleID($val)
{
$this->ArticleID =  $val;
}

function setStorageCount($val)
{
$this->StorageCount =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM tblstorage WHERE StorageID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->StorageID = $row->StorageID;

$this->ArticleID = $row->ArticleID;

$this->StorageCount = $row->StorageCount;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM tblstorage WHERE StorageID = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->StorageID = ""; // clear key for autoincrement

$sql = "INSERT INTO tblstorage ( ArticleID,StorageCount ) VALUES ( '$this->ArticleID','$this->StorageCount' )";
$result = $this->database->query($sql);
$this->StorageID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE tblstorage SET  ArticleID = '$this->ArticleID',StorageCount = '$this->StorageCount' WHERE StorageID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
